language: go
go:
  - 1.10.x
  - 1.11.x
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
git:
  depth: false
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo sh -c "echo 0 > /proc/sys/kernel/yama/ptrace_scope"; fi
  - go test -v -timeout 3m ./...
